# Generated by Django 3.1 on 2020-09-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign_up',
            old_name='u_email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='sign_up',
            old_name='u_mob_no',
            new_name='Mob_no',
        ),
        migrations.RenameField(
            model_name='sign_up',
            old_name='u_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='sign_up',
            old_name='u_password',
            new_name='Password',
        ),
        migrations.RemoveField(
            model_name='sign_up',
            name='u_address',
        ),
        migrations.RemoveField(
            model_name='sign_up',
            name='u_img',
        ),
        migrations.AddField(
            model_name='sign_up',
            name='Address',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sign_up',
            name='Img',
            field=models.ImageField(default='', null=True, upload_to='static/users/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='', upload_to='static/products/'),
        ),
    ]
