# Generated by Django 3.1 on 2020-09-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200919_1514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sign_up',
            new_name='sign_up_info',
        ),
    ]
