# Generated by Django 3.1.1 on 2020-09-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200919_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_to_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('user_id', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('order_date', models.DateField()),
            ],
        ),
    ]
