# Generated by Django 3.1.1 on 2020-09-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_add_to_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_to_cart',
            old_name='order_date',
            new_name='add_date',
        ),
    ]
